[package]
name = "bpf-utils"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
addr2line = { path = "../../addr2line" }
anyhow = "1.0.38"
libc = "0.2.82"
memmap = "0.7.0"
moria = { path = "../../moria" }
thiserror = "1.0.23"
