[package]
name = "bpf-helpers-sys"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[build-dependencies]
bindgen = "0.56.0"
proc-macro2 = "1.0.24"
quote = "1.0.8"
syn = { version = "1.0.58", features = ["full", "visit"] }

[dependencies]
cty = "0.2.1"
